plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
title: Thought processes
author: codinggambit
email: jayraohere@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is a description of a journey through many turns and tides.
  Some opinions on different experiences along this path

# social links
twitter_username: sanjaysrao88 # DO NOT include the @ character, or else the build will fail!
linkedin_username: sansrao
instagram_username: pret_connoissuer
github_username:  codinggambit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

# Google Analytics
google_analytics: UA-174451722-1

